//////////////////////////////////////////////////////////////////////////
//			Copyright (c) 2015 CEVA-DSP Inc
//////////////////////////////////////////////////////////////////////////
//	File Name	:	CDNNCodePackage.h
//	Version		:	
//	Created	By	:	Erez Natan
//////////////////////////////////////////////////////////////////////////


/*!
*\file
*\brief External defines and types header file
*\author Erez Natan <erez.natan@ceva - dsp.com>
*/


//=============================================================================
//							Global Code Package
//=============================================================================


#ifndef __CDNN_CODEPACKAGE_H
#define __CDNN_CODEPACKAGE_H


#define NetworkLayerNumber	86


#define CDNNLAYERACTFUNCTION0000	0
#define CDNNLAYERACTFUNCTION0001	0
#define CDNNLAYERACTFUNCTION0002	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0003	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0004	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0005	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0006	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0007	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0008	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0009	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0010	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0011	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0012	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0013	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0014	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0015	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0016	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0017	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0018	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0019	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0020	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0021	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0022	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0023	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0024	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0025	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0026	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0027	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0028	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0029	0
#define CDNNLAYERACTFUNCTION0030	0
#define CDNNLAYERACTFUNCTION0031	MathActivation1DReLUPlanarPost
#define CDNNLAYERACTFUNCTION0032	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0033	0
#define CDNNLAYERACTFUNCTION0034	0
#define CDNNLAYERACTFUNCTION0035	MathActivation1DReLUPlanarPost
#define CDNNLAYERACTFUNCTION0036	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0037	0
#define CDNNLAYERACTFUNCTION0038	0
#define CDNNLAYERACTFUNCTION0039	MathActivation1DReLUPlanarPost
#define CDNNLAYERACTFUNCTION0040	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0041	0
#define CDNNLAYERACTFUNCTION0042	0
#define CDNNLAYERACTFUNCTION0043	MathActivation1DReLUPlanarPost
#define CDNNLAYERACTFUNCTION0044	MathActivation1DReLUPlanar
#define CDNNLAYERACTFUNCTION0045	0
#define CDNNLAYERACTFUNCTION0046	0
#define CDNNLAYERACTFUNCTION0047	0
#define CDNNLAYERACTFUNCTION0048	0
#define CDNNLAYERACTFUNCTION0049	0
#define CDNNLAYERACTFUNCTION0050	0
#define CDNNLAYERACTFUNCTION0051	0
#define CDNNLAYERACTFUNCTION0052	0
#define CDNNLAYERACTFUNCTION0053	0
#define CDNNLAYERACTFUNCTION0054	0
#define CDNNLAYERACTFUNCTION0055	0
#define CDNNLAYERACTFUNCTION0056	0
#define CDNNLAYERACTFUNCTION0057	0
#define CDNNLAYERACTFUNCTION0058	0
#define CDNNLAYERACTFUNCTION0059	0
#define CDNNLAYERACTFUNCTION0060	0
#define CDNNLAYERACTFUNCTION0061	0
#define CDNNLAYERACTFUNCTION0062	0
#define CDNNLAYERACTFUNCTION0063	0
#define CDNNLAYERACTFUNCTION0064	0
#define CDNNLAYERACTFUNCTION0065	0
#define CDNNLAYERACTFUNCTION0066	0
#define CDNNLAYERACTFUNCTION0067	0
#define CDNNLAYERACTFUNCTION0068	0
#define CDNNLAYERACTFUNCTION0069	0
#define CDNNLAYERACTFUNCTION0070	0
#define CDNNLAYERACTFUNCTION0071	0
#define CDNNLAYERACTFUNCTION0072	0
#define CDNNLAYERACTFUNCTION0073	0
#define CDNNLAYERACTFUNCTION0074	0
#define CDNNLAYERACTFUNCTION0075	0
#define CDNNLAYERACTFUNCTION0076	0
#define CDNNLAYERACTFUNCTION0077	0
#define CDNNLAYERACTFUNCTION0078	0
#define CDNNLAYERACTFUNCTION0079	0
#define CDNNLAYERACTFUNCTION0080	0
#define CDNNLAYERACTFUNCTION0081	0
#define CDNNLAYERACTFUNCTION0082	0
#define CDNNLAYERACTFUNCTION0083	0
#define CDNNLAYERACTFUNCTION0084	0
#define CDNNLAYERACTFUNCTION0085	0

#endif //__CDNN_CODEPACKAGE_H
